language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable

env:
- FEATURES = ""

matrix:
  include:
    - rust: stable
      env:
        - FEATURES=""
    - rust: stable
      env:
        - FEATURES="--features make_dump"

before_cache:
- cargo install cargo-tarpaulin -f

before_script:
- rustup component add rustfmt
- rustup component add clippy

script: |
  echo FEATURES=$FEATURES
  cargo fmt --all -- --check
  cargo build --all-targets $CARGO_FEATURES
  cargo clippy --all-targets $CARGO_FEATURES
  cargo test --all-targets $CARGO_FEATURES

after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
