language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable

env:
- CARGO_FEATURES = ""
- CARGO_FEATURES = "make_dump"

before_cache:
- cargo install cargo-tarpaulin -f

before_script:
- rustup component add rustfmt
- rustup component add clippy

script:
- cargo fmt --all -- --check
- cargo build --all-targets --features $CARGO_FEATURES
- cargo clippy --all-targets --features $CARGO_FEATURES
- cargo test --all-targets --features $CARGO_FEATURES

after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
