language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable

env:
  - COVERAGE="" FEATURES=""
  - COVERAGE="yes" FEATURES="--features make_dump"

before_cache: |
  if [[ "$COVERAGE" == "yes" ]]; then
    cargo install cargo-tarpaulin -f
  fi

before_script:
- rustup component add rustfmt
- rustup component add clippy

script: |
  echo FEATURES=$FEATURES
  cargo fmt --all -- --check
  cargo build --all-targets $FEATURES
  cargo clippy --all-targets $FEATURES
  cargo test --all-targets $FEATURES

after_success: |
  if [[ "$COVERAGE" == "yes" ]]; then
    cargo tarpaulin --out Xml --all $FEATURES
    bash <(curl -s https://codecov.io/bash)
  fi
