language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable

before_cache:
- cargo install cargo-tarpaulin -f

before_script:
- rustup component add rustfmt

script:
- cargo clean
- cargo fmt --all -- --check
- cargo build
- cargo clippy --all-targets --all-features
- cargo test

after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
